<?

$this->breadcrumb = [
    $this->link($this->controller),
    $this->link($this->origin),
    $this->ucstring('add') . ' ' . $this->ucstring('sources')
];
$table = ['id' => 'source', 'pager' => true, 'filter' => true];
$table['header'] = [_('name'), _('type'), ''];

foreach ($this->sources as $source) {
    $table['data'][] = [
        $this->link($source),
        Model_NodeMapper::getNodeByEntity('type', 'Source', $source)->name,
        '<a class="button" href="/admin/source/link/sourceId/' . $source->id . '/rangeId/' . $this->origin->id . '">' .
        $this->ucstring('add') . '</a>'
    ];
}
?>
<? $this->table = $table; ?>
<?= $this->render('tableSorter.phtml'); ?>
