<? $form = $this->form; ?>
<?= $this->displayErrors($form); ?>
<?= $form->renderForm(false); ?>
<div>
    <div class="tableRow">
        <?= $form->name->renderLabel() ?>
        <div class="tableCell"><?= $form->name->renderViewHelper() ?></div>
    </div>
    <?= $this->displayTreeSelect($this->hierarchies, $form) ?>
    <div style="margin-top:1em;">
        <?= $form->description->renderLabel() ?>
        <div><?= $form->description->renderViewHelper() ?></div>
    </div>
    <div style="margin-top:1em;">
        <?= $form->modified->renderViewHelper() ?>
        <?= $form->formSubmit->renderViewHelper() ?>
        <? if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'insert'): ?>
            <?= $form->continue ?>
            <?= $form->continueButton->renderViewHelper() ?>
        <? endif ?>
    </div>
</div>
<?= '</form>' ?>
<? foreach ($this->hierarchies as $hierarchy) : ?>
    <? $dataVariable = $hierarchy->nameClean . 'TreeData'; ?>
    <?= $this->displayTreeOverlay($hierarchy->nameClean, $this->$dataVariable); ?>
<? endforeach ?>
