<?

$this->breadcrumb = [$this->ucstring('source')];
$this->buttonBar = $this->link('E33', 'insert');
$table = ['id' => 'source', 'filter' => true, 'pager' => true];
$table['header'] = [_('name'), _('type'), _('info')];
foreach ($this->sources as $source) {
    $type = Model_NodeMapper::getNodeByEntity('Source', $source);
    $typeName = ($type->rootId) ? $type->name : '';
    $table['data'][] = [
        $this->link($source),
        $typeName,
        $this->truncateString($source->description),
    ];
}
?>
<? $this->table = $table; ?>
<?= $this->render('tableSorter.phtml'); ?>
