<?

$this->breadcrumb = [$this->ucstring('reference')];
$this->buttonBar = '<a href="/admin/reference/insert/type/bibliography">+ Bibliography</a>';
$this->buttonBar .= '<a href="/admin/reference/insert/type/edition">+ Edition</a>';
$this->buttonBar .= '<a href="/admin/carrier/insert">+ Information Carrier</a>';
$table = ['id' => 'reference', 'pager' => true, 'filter' => true];
$table['header'] = [_('name'), _('class'), _('type')];
foreach ($this->references as $reference) {
    $type = reset($reference->types)[0]; // get first and only type
    $table['data'][] = [
        $this->link($reference),
        ($type->rootId) ? Model_NodeMapper::getById($type->rootId)->name : $type->name,
        ($type->rootId) ? $type->name : '',
    ];
}
?>
<? $this->table = $table; ?>
<?= $this->render('tableSorter.phtml') ?>
