<? $reference = $this->reference; ?>
<? $this->breadcrumb = [$this->link('reference', null, 'reference'), $reference->name]; ?>
<div id="tabs" class="tabsContainer">
    <ul>
        <li><a href="#tabInfo"><?= $this->ucstring('info') ?></a></li>
        <li><a href="#tabEvent"><?= $this->ucstring('events') ?> (<?= count($this->eventLinks) ?>)</a></li>
        <li><a href="#tabSource"><?= $this->ucstring('sources') ?> (<?= count($this->sourceLinks) ?>)</a></li>
        <li><a href="#tabActor"><?= $this->ucstring('actors') ?> (<?= count($this->actorLinks) ?>)</a></li>
        <li><a href="#tabPlace"><?= $this->ucstring('places') ?> (<?= count($this->placeLinks) ?>)</a></li>
    </ul>
    <div id="tabInfo">
        <div class="buttonBar">
            <?= $this->link($reference, 'update') ?>
            <?= $this->link($reference, 'delete') ?>
            <?= $this->bookmarkToggle($reference->id) ?>
        </div>
        <h1><?= $reference->name ?></h1>
        <?
            $table['data'] = [];
            foreach ($reference->getTypesForView() as $rootName => $nodes) {
                $table['data'][$rootName] = implode('<br/>', $nodes);
            }
            $this->table = $this->tableLog($table, 'entity', $reference->id);
        ?>
        <? $this->table = $this->tableLog($table, 'entity', $reference->id); ?>
        <?= $this->render('tableDataItem.phtml'); ?>
        <?= $this->description($reference) ?>
    </div>
    <div id="tabEvent">
        <?
        $tableEvent = ['id' => 'event', 'pager' => true, 'filter' => true];
        $tableEvent['header'] = [_('page'), _('event'), _('first'), _('last'), '', ''];
        foreach ($this->eventLinks as $link) {
            $text = $this->translate('refers_to') . ': ' . $link->range->name;
            $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                "')\" ";
            $deleteLink = '<div><a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $reference->id .
                '/#tabEvent' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a></div>';
            $tableEvent['data'][] = [
                $link->description,
                $this->link($link->range),
                $link->range->first,
                $link->range->last,
                '<a class="button" href="/admin/biblio/update/origin/reference/id/' . $link->id . '">' .
                    $this->ucstring('edit') . '</a>',
                $deleteLink
            ];
        }
        ?>
        <? $this->table = $tableEvent; ?>
        <?= $this->render('tableSorter.phtml'); ?>
    </div>
    <div id="tabSource">
        <?
        $tableSource = ['id' => 'source', 'pager' => true, 'filter' => true];
        $tableSource['header'] = [_('source'), _('type'), _('page'), '', ''];
        foreach ($this->sourceLinks as $link) {
            $text = $this->translate('refers_to') . ': ' . $link->range->name;
            $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                "')\" ";
            $deleteLink = '<div><a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $reference->id .
                '/#tabSource' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a></div>';
            $tableSource['data'][] = [
                $this->link($link->range),
                Model_NodeMapper::getNodeByEntity('Source', $link->range)->name,
                $link->description,
                '<a class="button" href="/admin/biblio/update/origin/reference/id/' . $link->id . '">' .
                    $this->ucstring('edit') . '</a>',
                $deleteLink
            ];
        }
        ?>
        <? $this->table = $tableSource; ?>
        <?= $this->render('tableSorter.phtml'); ?>
    </div>
    <div id="tabActor">
        <?
        $tableActor = ['id' => 'actor', 'pager' => true, 'filter' => true];
        $tableActor['header'] = [_('page'), _('actor'), _('class'), _('first'), _('last'), '', ''];
        foreach ($this->actorLinks as $link) {
            $text = $this->translate('refers_to') . ': ' . $link->range->name;
            $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                "')\" ";
            $deleteLink = '<a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $reference->id .
                '/#tabActor' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a>';
            $tableActor['data'][] = [
                $link->description,
                $this->link($link->range),
                $link->range->class->nameTranslated,
                $link->range->first,
                $link->range->last,
                '<a class="button" href="/admin/biblio/update/origin/reference/id/' . $link->id . '">' .
                    $this->ucstring('edit') . '</a>',
                $deleteLink
            ];
        }
        ?>
        <? $this->table = $tableActor; ?>
        <?= $this->render('tableSorter.phtml'); ?>
    </div>
    <div id="tabPlace">
        <?
        $tablePlace = ['id' => 'place', 'pager' => true, 'filter' => true];
        $tablePlace['header'] = [_('page'), _('name'), _('type'), _('first'), _('last'), '', ''];
        foreach ($this->placeLinks as $link) {
            $text = $this->translate('refers_to') . ': ' . $link->range->name;
            $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                "')\" ";
            $deleteLink = '<a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $reference->id .
                '/#tabPlace' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a>';
            $tablePlace['data'][] = [
                $link->description,
                $this->link($link->range),
                Model_NodeMapper::getNodeByEntity('Site', $link->range)->name,
                $link->range->first,
                $link->range->last,
                '<a class="button" href="/admin/biblio/update/origin/reference/id/' .
                    $link->id . '">' . $this->ucstring('edit') . '</a>',
                $deleteLink
            ];
        }
        ?>
        <? $this->table = $tablePlace; ?>
        <?= $this->render('tableSorter.phtml'); ?>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#tabs").tabs();
    });
</script>
