<? $this->breadcrumb = [$this->ucstring('login')]; ?>
<? $this->headTitle($this->ucstring('login')); ?>
<?= $this->form->setAction($this->url()); ?>
<? if (Model_SettingsMapper::getSetting('mail')): ?>
    <p>
        <a href="/admin/index/reset-password" style="text-decoration:none"><?= $this->ucstring("password_forgot") ?></a>
    </p>
<? endif ?>
<script type="text/javascript">
    $(function () {
        $("#username").focus();
    });
</script>
