<body>
    <?= $this->translate("mail_received_request_for") ?> <?= $this->mailUsername ?>
    <?= $this->translate("at") ?> <a href="<?= $this->mailHost ?>"><?= $this->mailHost ?></a><br><br>
    <?= $this->translate("mail_reset_password_link") ?>:<br>
    <a href="<?= $this->mailLink ?>"><?= $this->mailLink ?></a><br><br>
    <?= $this->translate("mail_link_is_valid_for") ?> <?= $this->mailResetConfirmHours ?>
    <?= $this->translate("hours") ?>.
</body>
