<?

$this->breadcrumb = [
    $this->link($this->controller),
    $this->link($this->origin),
    $this->ucstring('add') . ' ' . $this->ucstring('place')];

$table = ['id' => 'place', 'pager' => true, 'filter' => true];
$table['header'] = [_('name'), _('first'), _('last'), ''];
foreach ($this->objects as $object) {
    $table['data'][] = [
        $this->link($object),
        $object->first,
        $object->last,
        '<a class="button" href="/admin/place/link/placeId/' . $object->id . '/rangeId/' . $this->origin->id . '">' .
        $this->ucstring('add') . '</a>'
    ];
}
?>
<? $this->table = $table; ?>
<?= $this->render('tableSorter.phtml'); ?>
