<? $form = $this->form; ?>
<?= $this->displayErrors($form); ?>
<?= $form->renderForm(false); ?>
<div style="float:left">
    <div>
        <div class="tableRow">
            <?= $form->name->renderLabel() ?>
            <div class="tableCell"><?= $form->name->renderViewHelper() ?></div>
        </div>
        <?= $this->displayTreeSelect('site', $form) ?>
        <?= $this->displayAliasForm($form) ?>
        <?= $this->render('dateForm.phtml'); ?>
        <div class="tableRow">
            <div>
                <label><?= $this->ucstring('label_location_switch') ?></label>
            </div>
            <div class="tableCell">
                <span id="placeSwitcher" class="button"><?= $this->ucstring('show') ?></span>
            </div>
        </div>
        <div class="tableRow placeSwitch display-none">
            <?= $form->easting->renderLabel() ?>
            <div class="tableCell"><?= $form->easting->renderViewHelper() ?></div>
        </div>
        <div class="tableRow placeSwitch display-none">
            <?= $form->northing->renderLabel() ?>
            <div class="tableCell"><?= $form->northing->renderViewHelper() ?></div>
        </div>
        <div class="tableRow placeSwitch display-none">
            &nbsp;<div class="tableCell subformTitle"><?= $this->ucstring('situated_within') ?></div>
        </div>
        <?= $this->displayTreeSelectMulti('administrative', $form, $this->administratives) ?>
        <?= $this->displayTreeSelectMulti('historical', $form, $this->historicals) ?>
        <div style="margin-top:1em;">
            <?= $form->description->renderLabel() ?>
            <div><?= $form->description->renderViewHelper() ?></div>
        </div>
        <div style="margin-top:1em;margin-bottom:1em;">
            <?= $form->modified->renderViewHelper() ?>
            <?= $form->formSubmit->renderViewHelper() ?>
            <? if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'insert'): ?>
                <?= $form->continue ?> <?= $form->continueButton->renderViewHelper() ?>
            <? endif ?>
        </div>
    </div>
    <?= '</form>' ?>
</div>
<?= $this->displayTreeOverlay('site', $this->siteTreeData) ?>
<?= $this->displayTreeOverlay('administrative', $this->administrativeTreeData, true) ?>
<?= $this->displayTreeOverlay('historical', $this->historicalTreeData, true) ?>
<div id="map" class="map"></div>
<? $this->jsonData = Model_GisMapper::getJsonData(); ?>
<? if (!$this->jsonData): ?>
    <? $this->jsonData = ['marker' => '', 'search' => '']; // to show empty map ?>
<? endif ?>
<script type="text/javascript" src="/js/leaflet/map.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#aliasAdd").click(function () {
            ajaxAddField("alias", $("#aliasId").val());
        });
    });
</script>
