<? $form = $this->form; ?>
<?= $this->displayErrors($form); ?>
<?= $form->renderForm(false); ?>
<div style="float:left">
    <div>
        <div class="tableRow">
            <?= $form->name->renderLabel() ?>
            <div class="tableCell"><?= $form->name->renderViewHelper() ?></div>
        </div>
        <?= $this->displayAliasForm($form) ?>
        <?= $this->displayTreeSelect($this->hierarchies, $form) ?>
        <?= $this->render('dateForm.phtml'); ?>
        <?= $form->gisPoints->renderViewHelper() ?>
        <?= $form->gisPolygons->renderViewHelper() ?>
        <div style="margin-top:1em;">
            <?= $form->description->renderLabel() ?>
            <div><?= $form->description->renderViewHelper() ?></div>
        </div>
        <div style="margin-top:1em;margin-bottom:1em;">
            <?= $form->modified->renderViewHelper() ?>
            <?= $form->formSubmit->renderViewHelper() ?>
            <? if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'insert'): ?>
                <?= $form->continue ?> <?= $form->continueButton->renderViewHelper() ?>
            <? endif ?>
        </div>
    </div>
    <?= '</form>' ?>
</div>
<? foreach ($this->hierarchies as $hierarchy) : ?>
    <? $dataVariable = $hierarchy->nameClean . 'TreeData'; ?>
    <?= $this->displayTreeOverlay($hierarchy->nameClean, $this->$dataVariable); ?>
<? endforeach ?>
<div id="map" class="map"></div>
<script type="text/javascript" src="/js/leaflet/map.js"></script>
<script src="/js/leaflet/draw/leaflet.draw.js" type="text/javascript"></script>
<script src="/js/leaflet/shapedraw.js" type="text/javascript"></script>
<script src="/js/leaflet/draw/edithandler.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#aliasAdd").click(function () {
            ajaxAddField("alias", $("#aliasId").val());
        });
    });
</script>
