<? $this->breadcrumb = [$this->ucstring('place')]; ?>
<? $this->buttonBar = $this->link('E18', 'insert'); ?>
<?
$table = ['id' => 'place', 'pager' => true, 'filter' => true];
$table['header'] = [_('name'), _('type'), _('first'), _('last')];
foreach ($this->objects as $object) {
    $type = Model_NodeMapper::getNodeByEntity('Site', $object);
    $typeName = ($type && $type->rootId) ? $type->getNameDirected() : '';
    $table['data'][] = [
        $this->link($object),
        $typeName,
        $object->first,
        $object->last
    ];
}
$this->table = $table;
?>
<div style="float:left;">
    <?= $this->render('tableSorter.phtml') ?>
</div>
<? if ($this->gisData): ?>
    <div id="map" class="map"></div>
    <script type="text/javascript" src="/js/leaflet/map.js"></script>
<? endif ?>
