<? $this->breadcrumb = [$this->link('place'), $this->link($this->object), $this->ucstring('edit')]; ?>
<? if ($this->modifier): ?>
    <p class="error"><?= $this->translate('error_modified_info', $this->modifier) ?></p>
    <p><a class="button" href="/admin/place/update/id/<?= $this->object->id ?>"><?= $this->ucstring('reload') ?></a></p>
<? endif ?>
    <? //var_dump($this->polygons); ?>
    <? //var_dump($this->points); ?>
    <? //print_r($this->points2); ?>
    <script type="text/javascript">
        var gisPoints2 = <?= $this->points2 ?>;
    </script>
<?= $this->render('place/form.phtml'); ?>
