<? $form = $this->form; ?>
<?= $this->displayErrors($form); ?>
<?= $form->renderForm(false); ?>
<div>
    <? if ($form->referenceId): ?>
        <?= $this->displayTableSelect('reference', $form) ?>
    <? endif ?>
    <div class="tableRow">
        <?= $form->page->renderLabel() ?>
        <div class="tableCell"><?= $form->page->renderViewHelper() ?></div>
    </div>
    <div style="margin-top:1em;">
        <?= $form->formSubmit->renderViewHelper() ?>
    </div>
</div>
<?= '</form>' ?>
<? if ($form->referenceId): ?>
    <div id="referenceOverlay" class="overlay">
        <div id='referenceDialog' class="overlayContainer">
            <?
            $table = ['id' => 'reference', 'pager' => true, 'filter' => true];
            $table['header'] = [_('name'), _('class'), _('type')];
            foreach ($this->references as $reference) {
                $type = reset($reference->types)[0]; // get first and only type
                $table['data'][] = [
                    '<a onclick="selectFromTable(this, \'reference\', ' . $reference->id . ')">' . $reference->name . '</a>',
                    ($type->rootId) ? Model_NodeMapper::getById($type->rootId)->name : $type->name,
                    ($type->rootId) ? $type->name : '',
                ];
            }
            $this->table = $table;
            ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            createOverlay("reference", "<?= $this->ucstring('reference') ?>");
        });
    </script>
<? endif ?>

