<?
$this->breadcrumb = [
    $this->link('overview'),
    '<a href="/admin/overview/model">' . $this->ucstring('model') . '</a>',
    $this->ucstring('property')
];

$table = ['id' => 'property', 'pager' => true, 'filter' => true];
$table['header'] = [_('code'), _('name'), _('inverse'), _('domain'), _('range')];
foreach ($this->properties as $property) {
    $table['data'][] = [
        $this->link($property, 'view', $property->code),
        $property->nameTranslated,
        $property->nameInverseTranslated,
        $this->link($property->domain),
        $this->link($property->range)
    ];
}
$this->table = $table;
?>
<?= $this->render('tableSorter.phtml'); ?>
<script type="text/javascript">
    $.tablesorter.addParser({
        id: 'code',
        is: function (string, table, cell, $cell) {
            return false;
        },
        format: function (string, table, cell, cellIndex) {
            return string.replace(/P/, '').replace(/OA/, '100');
        },
        type: 'numeric'
    });
</script>
