<? $form = $this->form; ?>
<?= $this->displayErrors($form); ?>
<?= $form->renderForm(false); ?>
<div>
    <?= $this->displayTreeSelect($this->hierarchies, $form, True) ?>
    <div class="tableRow">
        <?= $form->name->renderLabel() ?>
        <div class="tableCell"><?= $form->name->renderViewHelper() ?></div>
    </div>
    <? if ($form->inverse_text): ?>
        <div class="tableRow">
            <?= $form->inverse_text->renderLabel() ?>
            <div class="tableCell"><?= $form->inverse_text->renderViewHelper() ?></div>
        </div>
    <? endif ?>
    <div style="margin-top:1em;">
        <?= $form->description->renderLabel() ?>
        <div><?= $form->description->renderViewHelper() ?></div>
    </div>
    <div style="margin-top:1em;">
        <?= $form->formSubmit->renderViewHelper() ?>
    </div>
</div>
<?= '</form>' ?>
<? foreach ($this->hierarchies as $hierarchy) : ?>
    <? $dataVariable = $hierarchy->nameClean . 'TreeData'; ?>
    <?= $this->displayTreeOverlay($hierarchy->nameClean, $this->$dataVariable); ?>
<? endforeach ?>
