<?
$this->breadcrumb = [$this->ucstring('hierarchy')];
$tabUl['system'] = '';
$tabDiv['system'] = '';
$tabUl['custom'] = '';
$tabDiv['custom'] = '';
foreach ($this->types as $id => $type) {
    $menu = ($type->system) ? 'system' : 'custom';
    $tabUl[$menu] .= '<li><a href="#tab' . $type->id . '">' . $type->name . '</a></li>';
    $tabDiv[$menu] .= '<div id="tab' . $type->id . '"><div class="buttonBar"><a id="add' . $type->id . '"
        onclick="addForm(' . $type->id . ', ' . (int) $type->directional . ');">+</a>';
    if (!$type->system && (in_array(Zend_Registry::get('user')->group, ['admin', 'manager']))) {
        $tabDiv[$menu] .= '
            <a href="/admin/hierarchy/update-hierarchy/id/' . $type->id . '">' . $this->ucstring('edit') . '</a>
            <a href="/admin/hierarchy/delete/id/' . $type->id . '">' . $this->ucstring('delete') . '</a>';
    }
    $tabDiv[$menu] .= '</div><div id="form' . $type->id . '"></div>';
    if ($type->subs) {
        global $printRecursiveTypes;
        $printRecursiveTypes = '';
        $tabDiv[$menu] .= recursiveTypes($type);
    }
    $tabDiv[$menu] .= '</div>';
}
if (in_array(Zend_Registry::get('user')->group, ['admin', 'manager'])) {
    $tabUl['custom'] .= '<a class="button" href="/admin/hierarchy/insert-hierarchy">+ ' . $this->ucstring('hierarchy') . '</a>';
}
?>
<div id="tabsMenu" class="tabsContainer">
    <ul>
        <li><a href="#menuTabSystem"><?= $this->ucstring('system') ?></a></li>
        <li><a href="#menuTabCustom"><?= $this->ucstring('custom') ?></a></li>
    </ul>
    <div id="menuTabSystem" style="padding: 0;">
        <div id="tabsSystem" class="tabsContainer">
            <ul><?= $tabUl['system'] ?></ul>
            <?= $tabDiv['system'] ?>
        </div>
    </div>
    <div id="menuTabCustom" style="padding: 0;" >
        <div id="tabsCustom" class="tabsContainer">
            <ul><?= $tabUl['custom'] ?></ul>
            <?= $tabDiv['custom'] ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $("#tabsMenu").tabs();
        $("#tabsSystem").tabs().addClass("ui-tabs-vertical");
        $("#tabsCustom").tabs().addClass("ui-tabs-vertical");
    });
    function validateName() {
        if ($.trim($("#name").val()).length > 0) {
            return true;
        }
        alert("<?= $this->ucstring('error_name_empty') ?>");
        return false;
    }
    function addForm(superId, directional) {
        $(".insertTypeForm").remove();
        form = '<form onsubmit="return validateName();" class="insertTypeForm" id="insertTypeForm" method="post" action="/admin/hierarchy/insert/superId/' + superId + '">';
        form += '<input type="text" name="name" id="name" class="required" placeholder="<?= $this->ucstring('name') ?>">';
        if (directional === 1) {
            form += '<input type="text" name="inverse" placeholder="<?= $this->ucstring('inverse') ?>">';
        }
        form += '<input type="submit" class="submit" value="<?= $this->ucstring('add') ?>"></form>';
        $('#form' + superId).append(form);
    }
</script>
<?

function recursiveTypes($type, $level = 0) {
    global $printRecursiveTypes;
    foreach ($type->subs as $subType) {
        if ($subType->subs) {
            $printRecursiveTypes .= printType($subType, $level);
            recursiveTypes($subType, $level + 1);
        } else {
            $printRecursiveTypes .= printType($subType, $level);
        }
    }
    return $printRecursiveTypes;
}

function printType($type, $level) {
    $directional = ($type->directional) ? 1 : 0;
    $html = '<a style="margin-left:' . $level . 'em;" href="/admin/hierarchy/view/id/' . $type->id . '">' . $type->name . '</a> ';
    $html .= '<a class="button add" id="add' . $type->id . '" onclick="addForm(' . $type->id . ', ' . $directional . ');">+</a> ';
    $html .= '<div style="margin-top:0.4em;margin-bottom:0.4em;margin-left:' . $level . 'em;" id="form' . $type->id . '"></div>';
    return $html;
}
