<?
$this->breadcrumb = [$this->ucstring('hierarchy')];
$tabUl['system'] = '';
$tabDiv['system'] = '';
$tabUl['custom'] = '';
$tabDiv['custom'] = '';
foreach ($this->nodes as $hierarchy => $rootNode) {
    foreach ($rootNode as $item) {
        $node = $item['node'];
        $tabUl[$hierarchy] .= '<li><a href="#tab' . $node->id . '">' . $node->name . '</a></li>';
        $tabDiv[$hierarchy] .= '<div id="tab' . $node->id . '"><p><strong>' . $node->name . '</strong></p>';
        $tabDiv[$hierarchy] .= '
            <div style="float:left;margin-right:3em;">
                <div class="buttonBar" style="margin-bottom:0.5em;">
                    <form method="post" action="/admin/hierarchy/insert/id/' . $node->id . '" style="margin-bottom:1em;">
                        <input class="tree-filter" id="' . $node->id . '-tree-search" placeholder="Filter" style="width:8em;" name="name"/>
                        <input type="hidden" name="mode" value="insert" />
                        <button value="insert" name="submit" type="submit">+</button>';
        if (!$node->system && (in_array(Zend_Registry::get('user')->group, ['admin', 'manager']))) {
            $tabDiv[$hierarchy] .= ' <a href="/admin/hierarchy/update-hierarchy/id/' . $node->id . '">' .
                $this->ucstring('edit') . '</a>' . $this->link($node, 'delete');
        }
        $tabDiv[$hierarchy] .= '</form></div>' . $item['tree'] . '</div>';
        $tabDiv[$hierarchy] .= '<div style="float:left;">';
        if ($node->forms) {
            $tabDiv[$hierarchy] .= '<p style="margin-top:0">' . $this->ucstring('forms') . ':</strong> ';
            foreach ($node->forms as $form) {
                $tabDiv[$hierarchy] .= $form['name'] . ', ';
            }
            $tabDiv[$hierarchy] = rtrim($tabDiv[$hierarchy], ", ");
            $tabDiv[$hierarchy] .= '</p>';
        }
        if ($node->description) {
            $tabDiv[$hierarchy] .= '<p style="width:500px;">' . $node->description . '</p>';
        }
        $tabDiv[$hierarchy] .= '</div></div>';
    }
}

if (in_array(Zend_Registry::get('user')->group, ['admin', 'manager'])) {
    $tabUl['custom'] .=
        '<a class="button" href="/admin/hierarchy/insert-hierarchy">+ ' . $this->ucstring('hierarchy') . '</a>';
}
?>
<div id="tabsMenu" class="tabsContainer">
    <ul>
        <li><a href="#menuTabSystem"><?= $this->ucstring('system') ?></a></li>
        <li><a href="#menuTabCustom"><?= $this->ucstring('custom') ?></a></li>
    </ul>
    <div id="menuTabSystem" style="padding: 0;" class="tabContent">
        <div id="tabsSystem" class="tabsContainer">
            <ul><?= $tabUl['system'] ?></ul>
            <?= $tabDiv['system'] ?>
        </div>
    </div>
    <div id="menuTabCustom" style="padding: 0;" class="tabContent">
        <div id="tabsCustom" class="tabsContainer">
            <ul><?= $tabUl['custom'] ?></ul>
            <?= $tabDiv['custom'] ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#tabsMenu").tabs();
        $("#tabsSystem").tabs().addClass("ui-tabs-vertical");
        $("#tabsCustom").tabs().addClass("ui-tabs-vertical");
        openParentTab();
    });
    function openParentTab() {
        locationHash = location.hash.substring(1);
        console.log(locationHash);
        if (locationHash) {
            var hash = $('#' + locationHash);
            if (hash.length) {
                if (hash.closest(".tabContent").length) {
                    var tabNumber = hash.closest(".tabContent").index();
                    $("#tabsMenu").tabs({active: tabNumber - 1});
                    hash.get(0).scrollIntoView();
                    setTimeout(function () {
                        hash.get(0).scrollIntoView();
                    }, 1000);
                }
            }
        }
    }
</script>
