<? $node = $this->node; ?>
<? $this->breadcrumb = [$this->link('hierarchy')]; ?>
<? if ($this->root): ?>
    <? $this->breadcrumb[] = '<a href="/admin/hierarchy#tab' . $this->root->id . '">' . $this->root->name . '</a>'; ?>
    <? $this->buttonBar = $this->link($node, 'update'); ?>
    <? if (!$this->linksEntities && !$this->linksProperties && empty($node->subs)): ?>
        <? $this->buttonBar .= $this->link($node, 'delete'); ?>
    <? endif ?>
<? endif ?>
<? $this->breadcrumb[] = $node->name; ?>
<div id="tabs" class="tabsContainer">
    <ul>
        <li><a href="#tabInfo"><?= $this->ucstring('info') ?></a></li>
        <? if ($node->subs): ?>
            <li><a href="#tabSub"><?= $this->ucstring('subs') ?> (<?= count($node->subs) ?>)</a></li>
        <? endif ?>
        <? if ($this->linksEntities): ?>
            <li><a href="#tabEntity"><?= $this->ucstring('entities') ?> (<?= count($this->linksEntities) ?>)</a></li>
        <? endif ?>
        <? if ($this->linksProperties): ?>
            <li><a href="#tabProperty"><?= $this->ucstring('properties') ?> (<?= count($this->linksProperties) ?>)</a></li>
        <? endif ?>
    </ul>
    <div id="tabInfo">
        <h1><?= $node->name ?></h1>
        <? $table = []; ?>
        <? if ($node->superId): ?>
            <? $table['data']['super'] = $this->link(Model_NodeMapper::getById($node->superId)); ?>
        <? endif ?>
        <? $this->table = $this->tableLog($table, 'entity', $node->id); ?>
        <?= $this->render('tableDataItem.phtml'); ?>
        <? $this->description($node); ?>
    </div>
    <? if ($node->subs): ?>
        <div id="tabSub">
            <? foreach ($node->subs as $sub): ?>
                <p><?= $this->link($sub) ?></p>
            <? endforeach ?>
        </div>
    <? endif ?>
    <? if ($this->linksEntities): ?>
        <div id="tabEntity">
            <?
            $table = ['id' => 'search', 'pager' => true, 'filter' => true];
            $table['header'] = [_('name'), _('class'), _('first'), _('last')];
            foreach ($this->linksEntities as $entity) {
                $table['data'][] = [
                    $this->link($entity),
                    $this->link($entity->class),
                    $entity->first,
                    $entity->last
                ];
            }
            ?>
            <? $this->table = $table; ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
    <? endif ?>
    <? if ($this->linksProperties): ?>
        <div id="tabProperty">
            <? foreach ($this->linksProperties as $link): ?>
                <?
                $table = ['id' => 'search', 'pager' => true, 'filter' => true];
                $table['header'] = [_('domain'), _('range')];
                foreach ($this->linksProperties as $link) {
                    $table['data'][] = [
                        $this->link($link->domain->domain),
                        $this->link($link->domain->range)
                    ];
                }
                ?>
            <? endforeach ?>
            <? $this->table = $table; ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
    <? endif ?>
</div>
<script type="text/javascript">
    $(function () {
        $("#tabs").tabs();
    });
</script>
