<? $this->buttonBar = '<a href="/admin/settings/update">' . $this->ucstring('edit') . '</a>'; ?>
<? $this->breadcrumb = [$this->ucstring('settings')]; ?>
<?

$logArray = [
    0 => 'emergency',
    1 => 'alert',
    2 => 'critical',
    3 => 'error',
    4 => 'warn',
    5 => 'notice',
    6 => 'info',
    7 => 'debug'
];

$settings = Model_SettingsMapper::getSettings();
$settingsGroups[_('general')] = [
    'sitename' => $settings['sitename'],
    'language' => Model_LanguageMapper::getById($settings['language'])->name,
    'maintenance' => $settings['maintenance'] ? $this->ucstring('on') : $this->ucstring('off'),
    'offline' => $settings['offline'] ? $this->ucstring('on') : $this->ucstring('off'),
    'log_level' => $logArray[$settings['log_level']],
    'default_table_rows' => $settings['default_table_rows'],
];

$settingsGroups[_('mail')] = [
    'mail' => $settings['mail'] ? $this->ucstring('on') : $this->ucstring('off'),
    'mail_transport_username' => $settings['mail_transport_username'],
    'mail_transport_password' => $settings['mail_transport_password'],
    'mail_transport_ssl' => $settings['mail_transport_ssl'],
    'mail_transport_auth' => $settings['mail_transport_auth'],
    'mail_transport_port' => $settings['mail_transport_port'],
    'mail_transport_host' => $settings['mail_transport_host'],
    'mail_from_email' => $settings['mail_from_email'],
    'mail_from_name' => $settings['mail_from_name'],
    'mail_recipients_login' => $settings['mail_recipients_login'],
    'mail_recipients_feedback' => $settings['mail_recipients_feedback'],
];

$settingsGroups[_('authentication')] = [
    'random_password_length' => $settings['random_password_length'],
    'reset_confirm_hours' => $settings['reset_confirm_hours'],
    'failed_login_tries' => $settings['failed_login_tries'],
    'failed_login_forget_minutes' => $settings['failed_login_forget_minutes']
];

?>
<div id="tabs" class="tabsContainer">
    <ul>
        <? foreach ($settingsGroups as $name => $items): ?>
            <li><a href="#tab<?= ucfirst($name) ?>"><?= $this->ucstring($name) ?></a></li>
        <? endforeach ?>
    </ul>
    <? foreach ($settingsGroups as $name => $items): ?>
        <div id="tab<?= ucfirst($name) ?>">
            <div class="dataTable">
                <? foreach ($items as $name => $value): ?>
                    <div><div><?= $this->ucstring($name) ?></div><div><?= $value ?></div></div>
                <? endforeach ?>
            </div>
        </div>
    <? endforeach ?>
</div>
<script type="text/javascript">
    $(function () {
        $("#tabs").tabs();
    });
</script>
