<?= $this->doctype() ?>
<? $version = Zend_Registry::get('config')->get('version') ?>
<? $user = Zend_Registry::get('user'); ?>
<? $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?>
<? $menu = ['about', 'model', 'changelog', 'credits', 'contact']; ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?= $this->headTitle() ?>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32" />
        <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" />
        <meta name="theme-color" content="#ffffff" />
        <link href="/css/reset.css" rel="stylesheet" />
        <link rel="stylesheet" href="/js/jquery/ui/jquery.smoothness.ui.min.css" />
        <link rel="stylesheet" href="/js/jquery/jstree/themes/default/style.min.css" />
        <? foreach (['admin_style.css', 'admin_color.css', 'admin_images.css'] as $styleSheet): ?>
            <link rel="stylesheet" href="/css/<?= $styleSheet ?>?v=<?= $version ?>" />
        <? endforeach ?>
        <script type="text/javascript" src="/js/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="/js/jquery/tablesorter/tablesorter.min.js"></script>
        <script type="text/javascript" src="/js/jquery/tablesorter/tablesorter.widgets.js"></script>
        <script type="text/javascript" src="/js/jquery/tablesorter/tablesorter.pager.js"></script>
    </head>
    <body>
        <div id="adminHead">
            <div id="adminLogo"><a href="/"></a></div>
            <div id="websiteName">
                <? if (strpos(filter_input(INPUT_SERVER, 'HTTP_HOST'), 'local') !== false): ?>
                    <span class="info">local</span>
                <? endif ?>
                <? if (Model_SettingsMapper::getSetting('offline') && in_array($user->group, ['admin', 'editor'])): ?>
                    <span class="error">Offline</span>
                <? endif ?>
                <? if (Model_SettingsMapper::getSetting('maintenance') && $user->group == 'admin'): ?>
                    <span class="error">Maintenance</span>
                <? endif ?>
                <br/>
                <? foreach ($this->messenger() as $message): ?>
                    <br/>
                    <div class='message <?= $message['type'] ?>'>
                        <?= $this->translate($message['message']) ?>
                    </div>
                <? endforeach ?>
            </div>
            <div id="adminUser">
                <? if ($user->active): ?>
                    <div id="greeting">
                        <?= $this->ucstring('hello') ?> <?= $user->username ?>
                    </div>
                    <div>
                        <a href="/admin/profile"><?= $this->ucstring('profile') ?></a> |
                        <a href="/admin/index/logout"><?= $this->ucstring('logout') ?></a>
                    </div>
                <? endif ?>
                <div id="changelog">
                    <a href="/default/changelog"><?= $this->ucstring('version') ?> <?= $version ?></a>
                </div>
                <div id="languageMenu">
                    <?= $this->languageMenu() ?>
                    <div class="languageSeparator">|</div>
                    <? if ($user->active): ?>
                        <a href="/admin"><?= $this->ucstring('admin') ?></a>
                    <? else: ?>
                        <a href="/admin"><?= $this->ucstring('login') ?></a>
                    <? endif ?>
                </div>
            </div>
        </div>
        <div style="clear:both;"></div>
        <div id="adminMenu">
            <? foreach ($menu as $item): ?>
                <? $menuHighlight = (isset($this->menuHighlight))? $this->menuHighlight : $controller; ?>
                 <div <?= ($item == $menuHighlight) ? 'class="selected"' : '' ?>>
                    <a href="/<?= $item ?>"><?= $this->ucstring($item) ?></a>
                </div>
            <? endforeach ?>
        </div>
        <? if (isset($this->breadcrumb)) : ?>
            <div id="breadcrumb">
                <? $breadcrumb = []; ?>
                <? foreach ($this->breadcrumb as $crumb): ?>
                    <? if (is_array($crumb)): ?>
                        <? $breadcrumb[] = '<div><a href="' . $crumb[1] . '">' . $crumb[0] . '</a></div>'; ?>
                    <? else: ?>
                        <? $breadcrumb[] = '<div><span>' . $crumb . '</span></div>'; ?>
                    <? endif ?>
                <? endforeach ?>
                <?= implode(' <div class="separator">></div> ', $breadcrumb) ?>
            </div>
        <? endif ?>
        <div id="content">
            <?= $this->layout()->content ?>
            <? if (strpos(filter_input(INPUT_SERVER, 'HTTP_HOST'), 'craws.net') !== false): ?>
                <div id="poweredBy">
                    Another
                    <a href="http://openatlas.eu" onclick="window.open(this.href); return false;">OpenAtlas</a>
                    project powered by
                    <a href="http://craws.net" onclick="window.open(this.href); return false;"> craws.net</a>
                </div>
            <? endif ?>
        </div>
    </body>
</html>
