<?
    $class = $this->class;
    $this->breadcrumb = [
        $this->link('overview'),
        '<a href="/admin/overview/model">' . $this->ucstring('model') . '</a>',
        $class->code
    ]
?>
<div style="float:left;padding-right:2em;">
    <p><strong><?= $this->ucstring('info') ?></strong></p>
    <? $table['data'] = [_('code') => $class->code, _('name') => $class->nameTranslated]; ?>
    <? $this->table = $table; ?>
    <? echo $this->render('tableDataItem.phtml'); ?>
</div>
<?
foreach ([
    'super' => $class->getSuper(),
    'subs' => $class->getSub(),
    _('domain_for') => $this->domains,
    _('range_for') => $this->ranges
] as $title => $array):
    ?>
    <? if ($array): ?>
        <div style="float:left;padding-right:2em;">
            <p><strong><?= $this->ucstring($title) ?></strong></p>
            <? foreach ($array as $item): ?>
                <p><?= $this->link($item, 'view', $item->getCodeName()) ?></p>
            <? endforeach ?><br/>
        </div>
    <? endif ?>
<? endforeach ?>
<div style="clear:both;"></div>
<? if ($class->commentTranslated): ?>
    <div class="description">
        <strong><?= $this->ucstring('comment') ?></strong>
        <p><?= $class->commentTranslated ?></p>
    </div>
<? endif ?>

