<?
    $this->breadcrumb = [$this->ucstring('changelog')];
    $versions['2.3.0']['date'] = '';
    $versions['2.3.0']['data']['feature'] = [
        764 => 'Improved hierachy overview',
        702 => 'Improved settings',
        707 => 'Improved performance',
        494 => 'Newsletter and registration mails',
        319 => 'SMTP settings in admin interface',
        693 => 'Event overview: show event dates if available',
        569 => 'Previous and next buttons',
    ];
    $versions['2.2.0']['date'] = '11.09.2016';
    $versions['2.2.0']['data']['feature'] = [
        547 => 'Map: multiple points and areas for Places',
        719 => 'Favicon support for current systems'
    ];
    $versions['2.1.0']['date'] = '18.08.2016';
    $versions['2.1.0']['data']['feature'] = [
        643 => 'Performance improvements',
        700 => 'Improved frontend',
        703 => 'Add multiple actors, events and places to source'
    ];
    $versions['2.1.0']['data']['fix'] = [
        696 => 'Add texts to source'
    ];
    $versions['2.0.0']['date'] = '19.06.2016';
    $versions['2.0.0']['data']['feature'] = [
        428 => 'Dynamic Types',
        687 => 'Remove required restriction from type fields'
    ];
    $versions['2.0.0']['data']['fix'] = [
        688 => 'Translation errors',
        689 => 'Show/Hide buttons'
    ];
    $versions['1.6.0']['date'] = '04.05.2016';
    $versions['1.6.0']['data']['feature'] = [
        340 => 'Multiuser capability',
        672 => 'Add multiple sources for event/actor/place',
        679 => 'Improved credits',
        683 => 'Tooltips for form fields and profile'
    ];
    $versions['1.6.0']['data']['fix'] = [
        674 => 'Place error occurs during saving'
    ];
    $versions['1.5.0']['date'] = '01.04.2016';
    $versions['1.5.0']['data']['feature'] = [
        564 => 'Add multiple entries for relation, member and involvement',
        586 => 'Bookmarks',
        671 => 'Redmine links for changelog'
    ];
    $versions['1.4.0']['date'] = '26.03.2016';
    $versions['1.4.0']['data']['feature'] = [
        528 => 'jsTree views for hierarchies',
        566 => 'Enhanced profile and site settings',
        580 => 'Change menu and structure for easier access to types',
        654 => 'New map layers',
        666 => 'Added Credits'
    ];
    $versions['1.3.0']['date'] = '28.02.2016';
    $versions['1.3.0']['data']['feature'] = [
        462 => 'Actor - add member to group from actor view',
        563 => 'Actor - insert and continue for relations and members',
        600 => 'Update of JavaScript libraries (for jsTree)',
        621 => 'Revised and more compact schema'
    ];
    $versions['1.3.0']['data']['fix'] = [
        601 => 'Application is very slow on some views',
        638 => 'Names with an apostrophe in a table not selectable'
    ];
    $versions['1.2.0']['date'] = '13.12.2015';
    $versions['1.2.0']['data']['feature'] = [
        499 => 'Actor - place tab with map',
        511 => 'Search - advanced features'
    ];
    $versions['1.2.0']['data']['fix'] = [
        547 => 'Prevent double submit',
        587 => 'Support multiple email recipients'
    ];
    $versions['1.1.0']['date'] = '09.11.2015';
    $versions['1.1.0']['data']['feature'] = [
        529 => 'Reference - Information Carrier',
        527 => 'New user groups - manager and readonly',
        540 => 'Help and FAQ site',
        555 => 'Source - additional text type "Source Transliteration"',
        556 => 'Actor - function for member not required anymore',
        560 => 'Newsletter and show email option in profile'
    ];
    $versions['1.1.0']['data']['fix'] = [
        551 => 'Model - Updating type bug',
        544 => 'Map - Form data lost after mapsearch',
        533 => 'Map - Markers outside of Map',
    ];
    $versions['1.0.0']['date'] = '11.10.2015';
    $versions['1.0.0']['data']['feature'] = [
        487 => 'Event - Acquisition of places',
        508 => 'Reference - Editions',
        504 => 'Option to add comments for entities in texts tab',
        495 => 'Layout - new OpenAtlas logo',
        412 => 'Layout - improved layout and color scheme',
        525 => 'Layout - overlays for tables in forms'
    ];
    $versions['0.11.0']['date'] = '11.09.2015';
    $versions['0.11.0']['data']['feature'] = [
        433 => 'Search functions'
    ];
    $versions['0.10.0']['date'] = '01.09.2015';
    $versions['0.10.0']['data']['feature'] = [
        429 => 'Actor - member of',
        472 => 'Actor - activity for event relations',
        483 => 'Actor - update for relations and involvements',
        486 => 'Place - administrative units and historical places',
        389 => 'Reference - bibliography',
        489 => 'Layout - overwork, multiple possibilities to create and link entities',
        421 => 'CRM link checker'
    ];
    $versions['0.9.0']['date'] = '12.07.2015';
    $versions['0.9.0']['data']['feature'] = [
        392 => 'Event',
        423 => 'Map - advanced features',
        474 => 'Layout - new tab based layout for views'
    ];
    $versions['0.8.0']['date'] = '18.06.2015';
    $versions['0.8.0']['data']['feature'] = [
        326 => 'Map - search, show existing places',
        425 => 'Actor - added gender type',
        425 => 'Place - multiple evidences possible',
        425 => 'Forms - add multiple types with ajax (e.g. aliases)'
    ];
    $versions['0.7.0']['date'] = '29.05.2015';
    $versions['0.7.0']['data']['feature'] = [
        403 => 'Physical things - places',
        403 => 'Actor - residence, appears first and last places',
        353 => 'Maps - with Leaflet (GIS)',
        420 => 'First and last dates in list views (e.g. actor, place)'
    ];
    $versions['0.6.0']['date'] = '13.05.2015';
    $versions['0.6.0']['data']['feature'] = [
        402 => 'Begin, end, birth and death for actors (precise and range)',
        402 => 'Begin, end for relations (precise and range)',
        346 => 'CRM - link checker',
        412 => 'Layout - New color scheme'
    ];
    $versions['0.6.0']['data']['fix'] = [
        410 => 'wrong domains for links'
    ];
    $versions['0.5.0']['date'] = '08.04.2015';
    $versions['0.5.0']['data']['feature'] = [
        377 => 'Type hierarchy (editable)',
        377 => 'Primary source type for documents',
        391 => 'Period hierarchy (editable)',
        391 => 'Periods for actors',
        365 => 'Actor to actor relations',
        386 => 'Filter for tables'
    ];
    $versions['0.4.0']['date'] = '23.02.2015';
    $versions['0.4.0']['data']['feature'] = [
        362 => 'Document - Insert, update, delete, add texts, link with actors',
        354 => 'Alternative names',
        360 => 'Layout - new default color theme',
        359 => 'Layout - options default and advanced',
        358 => 'Import CRM property hierachy',
        360 => 'Layout - new default color theme'
    ];
    $versions['0.4.0']['data']['fix'] = [
        357 => 'wrong range link in listview properties'
    ];
    $versions['0.3.0']['date'] = '10.02.2015';
    $versions['0.3.0']['data']['feature'] = [
        348 => 'Actor - begin and end dates',
        307 => 'Log user CRM data manipulation'
    ];
    $versions['0.3.0']['data']['fix'] = [
        344 => 'tablesorter IE 11 bug'
    ];
    $versions['0.2.0']['date'] = '18.01.2015';
    $versions['0.2.0']['data']['feature'] = [
        310 => 'Actor - insert, update, delete, list, view',
        337 => 'CRM - new OpenAtlas shortcuts'
    ];
    $versions['0.1.0']['date'] = '30.12.2014';
    $versions['0.1.0']['data']['feature'] = [
        318 => 'CRM - classes',
        318 => 'CRM - properties',
        318 => 'CRM - relations (super/sub classes, domains, ranges)',
        318 => 'OpenAtlas shortcuts'
    ];
    $versions['0.0.2']['date'] = '03.12.2014';
    $versions['0.0.2']['data']['feature'] = [
        306 => 'CICOC classes',
        308 => 'Database design',
        314 => 'Feedback form and translations'
    ];
    $versions['0.0.1']['date'] = '05.11.2014';
    $versions['0.0.1']['data']['feature'] = [
        0 => 'Initial version based on the "Zend Base" project from
            <a onclick="window.open(this.href); return false;" href="http://craws.net"> craws.net</a>'
    ];

    foreach ($versions as $version => $data) {
        $date = 'TBA';
        if ($data['date']) {
            $date = $this->printDate(new Zend_Date($data['date'], 'de'));
        }
        $html =  '<div class="changelog">
                <div class="changelogVersion">Version ' . $version . '</div>
                <div class="changelogDate">' . $date . '</div><p>';
        foreach($data['data'] as $tracker => $issue) {
            foreach($issue as $number => $subject) {
                if (!$number) {
                    $html .= $subject . '<br/>';
                    continue;
                }
                $html .= '&#8226; ' . ucfirst($tracker) . ' <a href="http://redmine.craws.net/issues/' . $number .
                    '" onclick="window.open(this.href);return false;">#' . $number . '</a>: ' .
                    $subject . '<br/>';
            }
        }
        echo $html . '</p></div>';
    }
