<? $this->breadcrumb = [$this->link('overview'), $this->ucstring('credits')]; ?>
<h1>Team</h1>
<h2>Stefan Eichert</h2>
<p>Idea and Concept, CIDOC-CRM Adaptions and Mappings, Map and Leaflet Implementation</p>
<h2>Alexander Watzinger</h2>
<p>
    Software Development, CIDOC-CRM Adaptions and Mappings<br/>
    <a href="http://craws.net" onclick="window.open(this.href);return false;">http://craws.net</a> -
    <a href="mailto:alexander.watzinger@craws.net">alexander.watzinger@craws.net</a>
</p>
<h2>Christof Rauchenberger</h2>
<p>
    System Administration<br/>
    <a href="http://craws.net" onclick="window.open(this.href);return false;">http://craws.net</a>
</p>
<h2>Jan Belik</h2>
<p>
    Graphic Design<br/>
    <a href="http://janbelik.com" onclick="window.open(this.href);return false;">http://janbelik.com</a>
</p>
<h2>Daniel Kittel</h2>
<p>Quality Assurance</p>

<h1>Funding</h1>
<p>Development was and is funded by several projects, grants, institutes and departments:</p>
<p>
    <a href="http://www.oeaw.ac.at/en/austrian-academy-of-sciences/" onclick="window.open(this.href);return false;">
        Austrian Academy of Sciences
    </a><br/>
    <a href="http://dpp.oeaw.ac.at/" onclick="window.open(this.href);return false;">DPP- Digitising Patterns of Power</a><br/>
    <a href="http://homepage.univie.ac.at/stefan.eichert/gkn/" onclick="window.open(this.href);return false;">
        Frontier, Contact Zone or No Man's Land
    </a><br/>
    <a href="https://www.fwf.ac.at/en/" onclick="window.open(this.href);return false;">FWF Austrian Science Fund</a><br/>
    <a href="https://oeaw.academia.edu/MappingMedievalConflict" onclick="window.open(this.href);return false;">
        MEDCON- Mapping Medieval Conflict
    </a><br/>
    <a href="http://www.oeaw.ac.at/imafo/arbeitsgruppen/fruehmittelalter/projekte-historische-identitaetsforschung/einzelprojekte/ostalpenraum-revisited/
       " onclick="window.open(this.href);return false;">Ostalpenraum-revisited</a><br/>
</p>

<h1>Contributors</h1>
<p>
    Bernhard Koschicek (DPP)<br/>
    Johannes Preiser-Kapeller (MEDCON)<br/>
    Katharina Winckler (DPP)<br/>
    Mihailo Popović (DPP)<br/>
    Petra Heinicker (MEDCON)<br/>
</p>