<? $this->breadcrumb = [$this->link('overview'), $this->ucstring('feedback')]; ?>
<p><?= $this->translate('feedback_intro') ?>:</p>
<p>
    - <?= $this->translate('feedback_redmine') ?>:
    <a href="http://redmine.craws.net/projects/uni" onclick="window.open(this.href); return false;">
        http://redmine.craws.net
    </a>
</p>
<? if ($this->feedbackEmail): ?>
<p>
    - <?= $this->translate('feedback_mail') ?>
    <a href="mailto:<?= $this->feedbackEmail ?>"><?= $this->feedbackEmail ?></a>
</p>
<? endif ?>
<? if (Model_SettingsMapper::getSetting('mail') && $this->feedbackEmail): ?>
    <?= $this->form->renderForm(false); ?>
    <p>- <?= $this->translate('feedback_form') ?></p>
    <div class="tableRow">
        <?= $this->form->subject->renderLabel() ?>
        <div class="tableCell"><?= $this->form->subject->renderViewHelper() ?></div>
    </div>
    <div style="padding:0.2em;">
    <?= $this->form->description->renderLabel() ?>
    </div>
    <div style="padding:0.2em;"><?= $this->form->description->renderViewHelper() ?></div>
    <div style="margin-top:1em;padding:0.2em;">
        <?= $this->form->formSubmit->renderViewHelper() ?>
    </div>
<? endif ?>
