<? $event = $this->event; ?>
<? $this->breadcrumb = [$this->link('event'), $event->name]; ?>
<div id="tabs" class="tabsContainer">
    <ul>
        <li><a href="#tabInfo"><?= $this->ucstring('info') ?></a></li>
        <? if ($event->name != $this->eventRootName): ?>
            <li><a href="#tabActor"><?= $this->ucstring('actors') ?> (<?= count($this->actorLinks) ?>)</a></li>
            <li><a href="#tabSource"><?= $this->ucstring('sources') ?> (<?= count($this->sourceLinks) ?>)</a></li>
            <li><a href="#tabReference"><?= $this->ucstring('references') ?> (<?= count($this->referenceLinks) ?>)</a></li>
        <? endif ?>
        <li><a href="#tabSub"><?= $this->ucstring('subs') ?> (<?= count($this->subs) ?>)</a></li>
    </ul>
    <div id="tabInfo">
        <? if ($event->name != $this->eventRootName): ?>
            <div class="buttonBar">
                <?= $this->link($event, 'update') ?>
                <?= $this->link($event, 'delete') ?>
                <?= $this->bookmarkToggle($event->id) ?>
            </div>
        <? endif ?>
        <h1><?= $event->name ?></h1>
        <?
        $table = [];
        /*if ($this->super && $this->super->id != $this->event->rootId) {
            $table['data'][_('super')] = $this->link($this->super);
        }*/
        if ($this->place) {
            $table['data'][_('place')] = $this->link($this->place);
        }
        if ($this->eventTypes) {
            $types = [];
            foreach ($this->eventTypes as $type) {
                $types[] = $this->link($type);
            }
            $table['data'][_('type')] = implode('<br/>', $types);
        }
        foreach (['OA5' => _('begin'), 'OA6' => _('end')] as $key => $label) {
            if (isset($this->dates[$key])) {
                $dates = $this->dates[$key];
                if (isset($dates['Exact date value'])) {
                    $table['data'][$label] = $this->printDate($dates['Exact date value']->date) . ' ' .
                        $dates['Exact date value']->description;
                } else {
                    $table['data'][$label] = $this->ucstring('between') . ' ' .
                        $this->printDate($dates['From date value']->date) . ' ' . $this->translate('and') . ' ' .
                        $this->printDate($dates['To date value']->date) . ' ' . $dates['From date value']->description;
                }
            }
        }
        if ($this->acquisitionRecipient) {
            $table['data']['recipient'] = $this->link($this->acquisitionRecipient);
        }
        if ($this->acquisitionDonor) {
            $table['data']['donor'] = $this->link($this->acquisitionDonor);
        }
        if ($this->acquisitionPlace) {
            $table['data']['acquisition'] = $this->link($this->acquisitionPlace);
        }
        $this->table = $this->tableLog($table, 'entity', $event->id);
        ?>
        <?= $this->render('tableDataItem.phtml'); ?>
        <?= $this->description($event) ?>
    </div>
    <? if ($event->name != $this->eventRootName): ?>
        <div id="tabActor">
            <div class="buttonBar">
                <a class="button" href="/admin/involvement/insert/origin/event/eventId/<?= $event->id ?>"><?= $this->ucstring('add') ?></a>
                <? foreach (Zend_Registry::get('config')->get('codeActor')->toArray() as $code): ?>
                    <?= $this->link($code, 'insert', null, $event); ?>
                <? endforeach ?>
            </div>
            <?
            $actorTable = ['id' => 'actor', 'pager' => true, 'filter' => true];
            $actorTable['header'] = [_('actor'), _('class'), _('activity'), 'Involvement', _('first'), _('last'), '', ''];
            foreach ($this->actorLinks as $link) {
                $involvement = "";
                $involvementType = Model_LinkPropertyMapper::getLinkedEntity($link, 'P2');
                if ($involvementType) {
                    $involvement = $involvementType->name;
                }
                $text = 'Involvement: ' . $link->range->name . ' ' . $link->property->nameInverseTranslated;
                $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                    "')\" ";
                $deleteButton = '<a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $event->id .
                    '/#tabActor' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a>';
                $dates = Model_DateMapper::getLinkDateRange($link);
                $actorTable['data'][] = [
                    $this->link($link->range),
                    $link->range->class->nameTranslated,
                    $link->property->nameInverseTranslated,
                    $involvement,
                    $dates['first'],
                    $dates['last'],
                    '<a class="button" href="/admin/involvement/update/origin/event/id/' . $link->id . '">' .
                    $this->ucstring('edit') . '</a>',
                    $deleteButton,
                ];
            }
            $this->table = $actorTable;
            ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
        <div id="tabSource">
            <div class="buttonBar">
                <a href="/admin/source/add/id/<?= $event->id ?>"><?= $this->ucstring('add') ?></a>
                <?= $this->link('E33', 'insert', null, $event); ?>
            </div>
            <?
            $sourceTable = ['id' => 'source', 'pager' => true, 'filter' => true];
            $sourceTable['header'] = [_('source'), _('type'), ''];
            foreach ($this->sourceLinks as $link) {
                $type = '';
                $sourceType = Model_NodeMapper::getNodeByEntity('Source', $link->domain);
                if ($sourceType) {
                    $type = $sourceType->name;
                }
                $text = $link->property->nameInverseTranslated . ': ' . $link->domain->name;
                $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                    "')\" ";
                $deleteButton = '<a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $event->id .
                    '/#tabSource' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a>';
                $sourceTable['data'][] = [
                    $this->link($link->domain),
                    $type,
                    $deleteButton
                ];
            }
            ?>
            <? $this->table = $sourceTable; ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
        <div id="tabReference">
            <div class="buttonBar">
                <a class="button" href="/admin/biblio/insert/id/<?= $event->id ?>"><?= $this->ucstring('add') ?></a>
            </div>
            <?
            $table = ['id' => 'reference', 'pager' => true, 'filter' => true];
            $table['header'] = [_('name'), _('page'), 'class', 'type', '', ''];
            foreach ($this->referenceLinks as $link) {
                $reference = $link->domain;
                $type = Model_LinkMapper::getLinkedEntity($reference, 'P2');
                $node = Model_NodeMapper::getById($type->id);
                $text = $this->ucstring('referred_by') . ': ' . $reference->name;
                $confirm = " onclick=\"return confirm('" . $this->ucstring($this->translate('confirm_remove', $text)) .
                    "')\" ";
                $deleteLink = '<div><a href="/admin/function/unlink/id/' . $link->id . '/entityId/' . $event->id .
                    '/#tabReference' . '" class="button"' . $confirm . '>' . $this->ucstring('remove') . '</a></div>';
                $table['data'][] = [
                    $this->link($reference),
                    $link->description,
                    Model_NodeMapper::getById($node->rootId)->name,
                    $node->name,
                        '<a class="button" href="/admin/biblio/update/origin/actor/id/' . $link->id . '">' .
                    $this->ucstring('edit') . '</a>',
                    $deleteLink
                ];
            }
            ?>
            <? $this->table = $table; ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
    <? endif ?>
    <div id="tabSub">
        <? if ($this->subs): ?>
            <? $table = ['id' => 'sub', 'pager' => true, 'filter' => true]; ?>
            <? $table['header'] = [_('event'), _('class'), _('first'), _('last')]; ?>
            <?
            foreach ($this->subs as $sub) {
                $table['data'][] = [
                    $this->link($sub),
                    $sub->class->nameTranslated,
                    $sub->first,
                    $sub->last
                ];
            }
            $this->table = $table;
            ?>
            <?= $this->render('tableSorter.phtml'); ?>
        <? endif ?>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#tabs").tabs();
    });
</script>
