<?php

$this->breadcrumb = [
    $this->link($this->controller),
    $this->link($this->origin),
    $this->ucstring('add') . ' ' . $this->ucstring('actor')];
$table = ['id' => 'actor', 'pager' => true, 'filter' => true];
$table['header'] = [_('actor'), _('class'), _('first'), _('last'), ''];

foreach ($this->actors as $actor) {
    $table['data'][] = [
        $this->link($actor),
        $actor->getClass()->nameTranslated,
        $actor->first,
        $actor->last,
        '<a class="button" href="/admin/actor/link/actorId/' . $actor->id . '/rangeId/' . $this->origin->id . '">' .
        $this->ucstring('add') . '</a>'
    ];
}
?>
<? $this->table = $table; ?>
<?= $this->render('tableSorter.phtml'); ?>
