<? $form = $this->form; ?>
<?= $this->displayErrors($form); ?>
<?= $form->renderForm(false); ?>
<div>
    <? if ($form->class): ?>
        <div class="tableRow">
            <?= $form->class->renderLabel() ?>
            <div class="tableCell"><?= $form->class->renderViewHelper() ?></div>
        </div>
    <? endif ?>
    <div class="tableRow">
        <?= $form->name->renderLabel() ?>
        <div class="tableCell"><?= $form->name->renderViewHelper() ?></div>
    </div>
    <?= $this->displayAliasForm($form) ?>
    <? if ($form->genderId): ?>
        <?= $this->displayTreeSelect('gender', $form) ?>
    <? endif ?>
    <? foreach ($this->hierarchies as $hierarchy) : ?>
        <?= $this->displayTreeSelect($hierarchy, $form) ?>
    <? endforeach ?>
    <?= $this->displayTableSelect('residence', $form) ?>
    <?= $this->displayTableSelect('appearsFirst', $form) ?>
    <?= $this->displayTableSelect('appearsLast', $form) ?>
    <?= $this->render('dateForm.phtml'); ?>
    <div style="margin-top:1em;">
        <?= $form->description->renderLabel() ?>
        <div><?= $form->description->renderViewHelper() ?></div>
    </div>
    <div style="margin-top:1em;">
        <?= $form->modified->renderViewHelper() ?>
        <?= $form->formSubmit->renderViewHelper() ?>
        <? if (!$this->event && Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'insert'): ?>
            <?= $form->continue ?>
            <?= $form->continueButton->renderViewHelper() ?>
        <? endif ?>
    </div>
</div>
<?= '</form>' ?>
<? if ($form->genderId): ?>
    <?= $this->displayTreeOverlay('gender', $this->genderTreeData) ?>
<? endif ?>
<? foreach ($this->hierarchies as $hierarchy) : ?>
    <? $dataVariable = $hierarchy->nameClean . 'TreeData'; ?>
    <?= $this->displayTreeOverlay($hierarchy->nameClean, $this->$dataVariable); ?>
<? endforeach ?>
<? foreach (['residence', 'appearsFirst', 'appearsLast'] as $placeTable): ?>
    <div id="<?= $placeTable ?>Overlay" class="overlay">
        <div id='<?= $placeTable ?>Dialog' class="overlayContainer">
            <?
            $table = ['id' => $placeTable, 'pager' => true, 'filter' => true];
            $table['header'] = [_('name'), _('first'), _('last')];
            foreach ($this->objects as $object) {
                $table['data'][] = [
                    '<a onclick="selectFromTable(this, \'' . $placeTable . '\', ' . $object->id . ')">' .
                        $object->name . '</a>',
                    $object->first,
                    $object->last,
                ];
            }
            $this->table = $table;
            ?>
            <?= $this->render('tableSorter.phtml'); ?>
        </div>
    </div>
<? endforeach ?>
<script type="text/javascript">
    $(document).ready(function () {
        createOverlay("residence", "<?= $this->ucstring('residence') ?>");
        createOverlay("appearsFirst", "<?= $this->ucstring('appears_first') ?>");
        createOverlay("appearsLast", "<?= $this->ucstring('appears_last') ?>");
        $("#aliasAdd").click(function () {
            ajaxAddField("alias", $("#aliasId").val());
        });
    });
</script>
